### PR TITLE
Fix dark mode detection

### LINKED ISSUE #2: Theme update synchronization with system theme change
# Problem
SwiftyMonaco automatically detects the theme, but it can't update it when it changes during execution.

# Solution
Use `UIKit` and `AppKit` features to handle this change.

### PR DESCRIPTION
**Pull request by pkasila**
#2 Now dark mode detection works perfectly fine: while initializing and just randomly changing appearance, everything changes and stays in the state before the change.

**Dark mode enabled**
image
**Dark mode disabled**
image

### CODE REVIEW

File: Sources/SwiftyMonaco/MonacoViewController.swift [hunk 1]
```diff
@@ -32,22 +32,48 @@ public class MonacoViewController: ViewController, WKUIDelegate, WKNavigationDel
         webView.layer?.backgroundColor = NSColor.clear.cgColor
         #endif
         view = webView
+        #if os(macOS)
+        DistributedNotificationCenter.default.addObserver(self, selector: #selector(interfaceModeChanged(sender:)), name: NSNotification.Name(rawValue: "AppleInterfaceThemeChangedNotification"), object: nil)
+        #endif
```
Comment (pkasila) [inline Sources/SwiftyMonaco/MonacoViewController.swift:37]: If InterfaceTheme changes, then we need to handle this

File: Sources/SwiftyMonaco/MonacoViewController.swift [hunk 2]
```diff
@@ -32,22 +32,48 @@ public class MonacoViewController: ViewController, WKUIDelegate, WKNavigationDel
...
         super.viewDidLoad()
         
+        loadMonaco()
+    }
+    
+    private func loadMonaco() {
         let myURL = Bundle.module.url(forResource: "index", withExtension: "html", subdirectory: "Resources")
         let myRequest = URLRequest(url: myURL!)
         webView.load(myRequest)
     }
```
Comment (pkasila) [inline Sources/SwiftyMonaco/MonacoViewController.swift:49]: Monaco loading process is moved to another function while testing ways to change appearance in the editor. I think it's better than it was because now it's more readable than before.

File: Sources/SwiftyMonaco/MonacoViewController.swift [hunk 3]
```diff
@@ -32,22 +32,48 @@ public class MonacoViewController: ViewController, WKUIDelegate, WKNavigationDel
...
     
+    // MARK: - Dark Mode
+    private func updateTheme() {
+        evaluateJavascript("""
+        (function(){
+            monaco.editor.setTheme('\(detectTheme())')
+        })()
+        """)
+    }
```
Comment (pkasila) [inline Sources/SwiftyMonaco/MonacoViewController.swift:58]: Javascript evaluation to setTheme in the MonacoEditor

File: Sources/SwiftyMonaco/MonacoViewController.swift [hunk 4]
```diff
@@ -32,22 +32,48 @@ public class MonacoViewController: ViewController, WKUIDelegate, WKNavigationDel
...
+    #if os(macOS)
+    @objc private func interfaceModeChanged(sender: NSNotification) {
+        updateTheme()
+    }
+    #else
+    public override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
+        super.traitCollectionDidChange(previousTraitCollection)
+        updateTheme()
+    }
+    #endif
```
Comment (pkasila) [inline Sources/SwiftyMonaco/MonacoViewController.swift:69]: Handling for interface changes on macOS and iPadOS with calling for `updateTheme`

File: Sources/SwiftyMonaco/MonacoViewController.swift [hunk 5]
```diff
@@ -32,22 +32,48 @@ public class MonacoViewController: ViewController, WKUIDelegate, WKNavigationDel
...
         #if os(macOS)
-        let x = NSAppearance.current.name
-        if x == .aqua {
-            return "vs"
-        } else {
+        if UserDefaults.standard.string(forKey: "AppleInterfaceStyle") == "Dark" {
             return "vs-dark"
+        } else {
+            return "vs"
         }
```
Comment (pkasila) [inline Sources/SwiftyMonaco/MonacoViewController.swift:77]: We use this way on macOS, because NSAppearance doesn't change immediately

File: Sources/SwiftyMonaco/MonacoViewController.swift [hunk 6]
```diff
@@ -118,6 +143,8 @@ public class MonacoViewController: ViewController, WKUIDelegate, WKNavigationDel
     }
```
Comment (pkasila) [inline Sources/SwiftyMonaco/MonacoViewController.swift:143]: Evaluation is moved to a separate function because it's being called from multiple places

**Review by pkasila — COMMENTED** [review]
Everything is fine!
